//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5 ../Grammars/OslcOrderBy.g 2013-06-26 12:12:44

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5")]
[System.CLSCompliant(false)]
public partial class OslcOrderByLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int ASTERISK=4;
	public const int CLOSE_CURLY_BRACE=5;
	public const int COMMA=6;
	public const int DIGIT=7;
	public const int DIRECTION=8;
	public const int DOT=9;
	public const int EOL=10;
	public const int MINUS=11;
	public const int OPEN_CURLY_BRACE=12;
	public const int PLUS=13;
	public const int PNAME_LN=14;
	public const int PNAME_NS=15;
	public const int PN_CHARS=16;
	public const int PN_CHARS_BASE=17;
	public const int PN_CHARS_U=18;
	public const int PN_LOCAL=19;
	public const int PN_PREFIX=20;
	public const int SCOPED_TERM=21;
	public const int SIMPLE_TERM=22;
	public const int TERMS=23;
	public const int WS=24;

    // delegates
    // delegators

	public OslcOrderByLexer()
	{
		OnCreated();
	}

	public OslcOrderByLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public OslcOrderByLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "../Grammars/OslcOrderBy.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_SCOPED_TERM();
	partial void LeaveRule_SCOPED_TERM();

	// $ANTLR start "SCOPED_TERM"
	[GrammarRule("SCOPED_TERM")]
	private void mSCOPED_TERM()
	{
		EnterRule_SCOPED_TERM();
		EnterRule("SCOPED_TERM", 1);
		TraceIn("SCOPED_TERM", 1);
		try
		{
			int _type = SCOPED_TERM;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:7:13: ( 'scoped_term' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:7:15: 'scoped_term'
			{
			DebugLocation(7, 15);
			Match("scoped_term"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("SCOPED_TERM", 1);
			LeaveRule("SCOPED_TERM", 1);
			LeaveRule_SCOPED_TERM();
		}
	}
	// $ANTLR end "SCOPED_TERM"

	partial void EnterRule_SIMPLE_TERM();
	partial void LeaveRule_SIMPLE_TERM();

	// $ANTLR start "SIMPLE_TERM"
	[GrammarRule("SIMPLE_TERM")]
	private void mSIMPLE_TERM()
	{
		EnterRule_SIMPLE_TERM();
		EnterRule("SIMPLE_TERM", 2);
		TraceIn("SIMPLE_TERM", 2);
		try
		{
			int _type = SIMPLE_TERM;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:8:13: ( 'simple_term' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:8:15: 'simple_term'
			{
			DebugLocation(8, 15);
			Match("simple_term"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("SIMPLE_TERM", 2);
			LeaveRule("SIMPLE_TERM", 2);
			LeaveRule_SIMPLE_TERM();
		}
	}
	// $ANTLR end "SIMPLE_TERM"

	partial void EnterRule_TERMS();
	partial void LeaveRule_TERMS();

	// $ANTLR start "TERMS"
	[GrammarRule("TERMS")]
	private void mTERMS()
	{
		EnterRule_TERMS();
		EnterRule("TERMS", 3);
		TraceIn("TERMS", 3);
		try
		{
			int _type = TERMS;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:9:7: ( 'terms' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:9:9: 'terms'
			{
			DebugLocation(9, 9);
			Match("terms"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("TERMS", 3);
			LeaveRule("TERMS", 3);
			LeaveRule_TERMS();
		}
	}
	// $ANTLR end "TERMS"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 4);
		TraceIn("WS", 4);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:68:5: ( ( ' ' | '\\t' | EOL )+ )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:68:7: ( ' ' | '\\t' | EOL )+
			{
			DebugLocation(68, 7);
			// ../Grammars/OslcOrderBy.g:68:7: ( ' ' | '\\t' | EOL )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_1 = input.LA(1);

				if (((LA1_1>='\t' && LA1_1<='\n')||LA1_1=='\r'||LA1_1==' '))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// ../Grammars/OslcOrderBy.g:
					{
					DebugLocation(68, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }

			DebugLocation(68, 25);
			 _channel=Hidden; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 4);
			LeaveRule("WS", 4);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_PNAME_NS();
	partial void LeaveRule_PNAME_NS();

	// $ANTLR start "PNAME_NS"
	[GrammarRule("PNAME_NS")]
	private void mPNAME_NS()
	{
		EnterRule_PNAME_NS();
		EnterRule("PNAME_NS", 5);
		TraceIn("PNAME_NS", 5);
		try
		{
			int _type = PNAME_NS;
			int _channel = DefaultTokenChannel;
			CommonToken p = default(CommonToken);

			// ../Grammars/OslcOrderBy.g:72:5: ( (p= PN_PREFIX )? ':' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:72:7: (p= PN_PREFIX )? ':'
			{
			DebugLocation(72, 8);
			// ../Grammars/OslcOrderBy.g:72:8: (p= PN_PREFIX )?
			int alt2=2;
			try { DebugEnterSubRule(2);
			try { DebugEnterDecision(2, false);
			int LA2_1 = input.LA(1);

			if (((LA2_1>='A' && LA2_1<='Z')||(LA2_1>='a' && LA2_1<='z')||(LA2_1>='\u00C0' && LA2_1<='\u00D6')||(LA2_1>='\u00D8' && LA2_1<='\u00F6')||(LA2_1>='\u00F8' && LA2_1<='\u02FF')||(LA2_1>='\u0370' && LA2_1<='\u037D')||(LA2_1>='\u037F' && LA2_1<='\u1FFF')||(LA2_1>='\u200C' && LA2_1<='\u200D')||(LA2_1>='\u2070' && LA2_1<='\u218F')||(LA2_1>='\u2C00' && LA2_1<='\u2FEF')||(LA2_1>='\u3001' && LA2_1<='\uD7FF')||(LA2_1>='\uF900' && LA2_1<='\uFDCF')||(LA2_1>='\uFDF0' && LA2_1<='\uFFFD')))
			{
				alt2 = 1;
			}
			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// ../Grammars/OslcOrderBy.g:72:8: p= PN_PREFIX
				{
				DebugLocation(72, 8);
				int pStart83 = CharIndex;
				int pStartLine83 = Line;
				int pStartCharPos83 = CharPositionInLine;
				mPN_PREFIX(); 
				p = new CommonToken(input, TokenTypes.Invalid, TokenChannels.Default, pStart83, CharIndex-1);
				p.Line = pStartLine83;
				p.CharPositionInLine = pStartCharPos83;

				}
				break;

			}
			} finally { DebugExitSubRule(2); }

			DebugLocation(72, 20);
			Match(':'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("PNAME_NS", 5);
			LeaveRule("PNAME_NS", 5);
			LeaveRule_PNAME_NS();
		}
	}
	// $ANTLR end "PNAME_NS"

	partial void EnterRule_PNAME_LN();
	partial void LeaveRule_PNAME_LN();

	// $ANTLR start "PNAME_LN"
	[GrammarRule("PNAME_LN")]
	private void mPNAME_LN()
	{
		EnterRule_PNAME_LN();
		EnterRule("PNAME_LN", 6);
		TraceIn("PNAME_LN", 6);
		try
		{
			int _type = PNAME_LN;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:76:5: ( PNAME_NS PN_LOCAL )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:76:7: PNAME_NS PN_LOCAL
			{
			DebugLocation(76, 7);
			mPNAME_NS(); 
			DebugLocation(76, 16);
			mPN_LOCAL(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("PNAME_LN", 6);
			LeaveRule("PNAME_LN", 6);
			LeaveRule_PNAME_LN();
		}
	}
	// $ANTLR end "PNAME_LN"

	partial void EnterRule_DIRECTION();
	partial void LeaveRule_DIRECTION();

	// $ANTLR start "DIRECTION"
	[GrammarRule("DIRECTION")]
	private void mDIRECTION()
	{
		EnterRule_DIRECTION();
		EnterRule("DIRECTION", 7);
		TraceIn("DIRECTION", 7);
		try
		{
			int _type = DIRECTION;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:81:5: ( PLUS | MINUS )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:
			{
			DebugLocation(81, 5);
			if (input.LA(1)=='+'||input.LA(1)=='-')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DIRECTION", 7);
			LeaveRule("DIRECTION", 7);
			LeaveRule_DIRECTION();
		}
	}
	// $ANTLR end "DIRECTION"

	partial void EnterRule_PN_CHARS_U();
	partial void LeaveRule_PN_CHARS_U();

	// $ANTLR start "PN_CHARS_U"
	[GrammarRule("PN_CHARS_U")]
	private void mPN_CHARS_U()
	{
		EnterRule_PN_CHARS_U();
		EnterRule("PN_CHARS_U", 8);
		TraceIn("PN_CHARS_U", 8);
		try
		{
			// ../Grammars/OslcOrderBy.g:88:5: ( PN_CHARS_BASE | '_' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:
			{
			DebugLocation(88, 5);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z')||(input.LA(1)>='\u00C0' && input.LA(1)<='\u00D6')||(input.LA(1)>='\u00D8' && input.LA(1)<='\u00F6')||(input.LA(1)>='\u00F8' && input.LA(1)<='\u02FF')||(input.LA(1)>='\u0370' && input.LA(1)<='\u037D')||(input.LA(1)>='\u037F' && input.LA(1)<='\u1FFF')||(input.LA(1)>='\u200C' && input.LA(1)<='\u200D')||(input.LA(1)>='\u2070' && input.LA(1)<='\u218F')||(input.LA(1)>='\u2C00' && input.LA(1)<='\u2FEF')||(input.LA(1)>='\u3001' && input.LA(1)<='\uD7FF')||(input.LA(1)>='\uF900' && input.LA(1)<='\uFDCF')||(input.LA(1)>='\uFDF0' && input.LA(1)<='\uFFFD'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("PN_CHARS_U", 8);
			LeaveRule("PN_CHARS_U", 8);
			LeaveRule_PN_CHARS_U();
		}
	}
	// $ANTLR end "PN_CHARS_U"

	partial void EnterRule_PN_CHARS();
	partial void LeaveRule_PN_CHARS();

	// $ANTLR start "PN_CHARS"
	[GrammarRule("PN_CHARS")]
	private void mPN_CHARS()
	{
		EnterRule_PN_CHARS();
		EnterRule("PN_CHARS", 9);
		TraceIn("PN_CHARS", 9);
		try
		{
			// ../Grammars/OslcOrderBy.g:93:5: ( PN_CHARS_U | MINUS | DIGIT | '\\u00B7' | '\\u0300' .. '\\u036F' | '\\u203F' .. '\\u2040' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:
			{
			DebugLocation(93, 5);
			if (input.LA(1)=='-'||(input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z')||input.LA(1)=='\u00B7'||(input.LA(1)>='\u00C0' && input.LA(1)<='\u00D6')||(input.LA(1)>='\u00D8' && input.LA(1)<='\u00F6')||(input.LA(1)>='\u00F8' && input.LA(1)<='\u037D')||(input.LA(1)>='\u037F' && input.LA(1)<='\u1FFF')||(input.LA(1)>='\u200C' && input.LA(1)<='\u200D')||(input.LA(1)>='\u203F' && input.LA(1)<='\u2040')||(input.LA(1)>='\u2070' && input.LA(1)<='\u218F')||(input.LA(1)>='\u2C00' && input.LA(1)<='\u2FEF')||(input.LA(1)>='\u3001' && input.LA(1)<='\uD7FF')||(input.LA(1)>='\uF900' && input.LA(1)<='\uFDCF')||(input.LA(1)>='\uFDF0' && input.LA(1)<='\uFFFD'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("PN_CHARS", 9);
			LeaveRule("PN_CHARS", 9);
			LeaveRule_PN_CHARS();
		}
	}
	// $ANTLR end "PN_CHARS"

	partial void EnterRule_PN_PREFIX();
	partial void LeaveRule_PN_PREFIX();

	// $ANTLR start "PN_PREFIX"
	[GrammarRule("PN_PREFIX")]
	private void mPN_PREFIX()
	{
		EnterRule_PN_PREFIX();
		EnterRule("PN_PREFIX", 10);
		TraceIn("PN_PREFIX", 10);
		try
		{
			// ../Grammars/OslcOrderBy.g:103:5: ( PN_CHARS_BASE ( ( PN_CHARS | DOT )* PN_CHARS )? )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:103:7: PN_CHARS_BASE ( ( PN_CHARS | DOT )* PN_CHARS )?
			{
			DebugLocation(103, 7);
			mPN_CHARS_BASE(); 
			DebugLocation(103, 21);
			// ../Grammars/OslcOrderBy.g:103:21: ( ( PN_CHARS | DOT )* PN_CHARS )?
			int alt4=2;
			try { DebugEnterSubRule(4);
			try { DebugEnterDecision(4, false);
			int LA4_1 = input.LA(1);

			if (((LA4_1>='-' && LA4_1<='.')||(LA4_1>='0' && LA4_1<='9')||(LA4_1>='A' && LA4_1<='Z')||LA4_1=='_'||(LA4_1>='a' && LA4_1<='z')||LA4_1=='\u00B7'||(LA4_1>='\u00C0' && LA4_1<='\u00D6')||(LA4_1>='\u00D8' && LA4_1<='\u00F6')||(LA4_1>='\u00F8' && LA4_1<='\u037D')||(LA4_1>='\u037F' && LA4_1<='\u1FFF')||(LA4_1>='\u200C' && LA4_1<='\u200D')||(LA4_1>='\u203F' && LA4_1<='\u2040')||(LA4_1>='\u2070' && LA4_1<='\u218F')||(LA4_1>='\u2C00' && LA4_1<='\u2FEF')||(LA4_1>='\u3001' && LA4_1<='\uD7FF')||(LA4_1>='\uF900' && LA4_1<='\uFDCF')||(LA4_1>='\uFDF0' && LA4_1<='\uFFFD')))
			{
				alt4 = 1;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// ../Grammars/OslcOrderBy.g:103:22: ( PN_CHARS | DOT )* PN_CHARS
				{
				DebugLocation(103, 22);
				// ../Grammars/OslcOrderBy.g:103:22: ( PN_CHARS | DOT )*
				try { DebugEnterSubRule(3);
				while (true)
				{
					int alt3=2;
					try { DebugEnterDecision(3, false);
					int LA3_1 = input.LA(1);

					if ((LA3_1=='-'||(LA3_1>='0' && LA3_1<='9')||(LA3_1>='A' && LA3_1<='Z')||LA3_1=='_'||(LA3_1>='a' && LA3_1<='z')||LA3_1=='\u00B7'||(LA3_1>='\u00C0' && LA3_1<='\u00D6')||(LA3_1>='\u00D8' && LA3_1<='\u00F6')||(LA3_1>='\u00F8' && LA3_1<='\u037D')||(LA3_1>='\u037F' && LA3_1<='\u1FFF')||(LA3_1>='\u200C' && LA3_1<='\u200D')||(LA3_1>='\u203F' && LA3_1<='\u2040')||(LA3_1>='\u2070' && LA3_1<='\u218F')||(LA3_1>='\u2C00' && LA3_1<='\u2FEF')||(LA3_1>='\u3001' && LA3_1<='\uD7FF')||(LA3_1>='\uF900' && LA3_1<='\uFDCF')||(LA3_1>='\uFDF0' && LA3_1<='\uFFFD')))
					{
						int LA3_2 = input.LA(2);

						if (((LA3_2>='-' && LA3_2<='.')||(LA3_2>='0' && LA3_2<='9')||(LA3_2>='A' && LA3_2<='Z')||LA3_2=='_'||(LA3_2>='a' && LA3_2<='z')||LA3_2=='\u00B7'||(LA3_2>='\u00C0' && LA3_2<='\u00D6')||(LA3_2>='\u00D8' && LA3_2<='\u00F6')||(LA3_2>='\u00F8' && LA3_2<='\u037D')||(LA3_2>='\u037F' && LA3_2<='\u1FFF')||(LA3_2>='\u200C' && LA3_2<='\u200D')||(LA3_2>='\u203F' && LA3_2<='\u2040')||(LA3_2>='\u2070' && LA3_2<='\u218F')||(LA3_2>='\u2C00' && LA3_2<='\u2FEF')||(LA3_2>='\u3001' && LA3_2<='\uD7FF')||(LA3_2>='\uF900' && LA3_2<='\uFDCF')||(LA3_2>='\uFDF0' && LA3_2<='\uFFFD')))
						{
							alt3 = 1;
						}


					}
					else if ((LA3_1=='.'))
					{
						alt3 = 1;
					}


					} finally { DebugExitDecision(3); }
					switch ( alt3 )
					{
					case 1:
						DebugEnterAlt(1);
						// ../Grammars/OslcOrderBy.g:
						{
						DebugLocation(103, 22);
						input.Consume();


						}
						break;

					default:
						goto loop3;
					}
				}

				loop3:
					;

				} finally { DebugExitSubRule(3); }

				DebugLocation(103, 38);
				mPN_CHARS(); 

				}
				break;

			}
			} finally { DebugExitSubRule(4); }


			}

		}
		finally
		{
			TraceOut("PN_PREFIX", 10);
			LeaveRule("PN_PREFIX", 10);
			LeaveRule_PN_PREFIX();
		}
	}
	// $ANTLR end "PN_PREFIX"

	partial void EnterRule_PN_LOCAL();
	partial void LeaveRule_PN_LOCAL();

	// $ANTLR start "PN_LOCAL"
	[GrammarRule("PN_LOCAL")]
	private void mPN_LOCAL()
	{
		EnterRule_PN_LOCAL();
		EnterRule("PN_LOCAL", 11);
		TraceIn("PN_LOCAL", 11);
		try
		{
			// ../Grammars/OslcOrderBy.g:108:5: ( ( PN_CHARS_U | DIGIT ) ( ( PN_CHARS | DOT )* PN_CHARS )? )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:108:7: ( PN_CHARS_U | DIGIT ) ( ( PN_CHARS | DOT )* PN_CHARS )?
			{
			DebugLocation(108, 7);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z')||(input.LA(1)>='\u00C0' && input.LA(1)<='\u00D6')||(input.LA(1)>='\u00D8' && input.LA(1)<='\u00F6')||(input.LA(1)>='\u00F8' && input.LA(1)<='\u02FF')||(input.LA(1)>='\u0370' && input.LA(1)<='\u037D')||(input.LA(1)>='\u037F' && input.LA(1)<='\u1FFF')||(input.LA(1)>='\u200C' && input.LA(1)<='\u200D')||(input.LA(1)>='\u2070' && input.LA(1)<='\u218F')||(input.LA(1)>='\u2C00' && input.LA(1)<='\u2FEF')||(input.LA(1)>='\u3001' && input.LA(1)<='\uD7FF')||(input.LA(1)>='\uF900' && input.LA(1)<='\uFDCF')||(input.LA(1)>='\uFDF0' && input.LA(1)<='\uFFFD'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(108, 30);
			// ../Grammars/OslcOrderBy.g:108:30: ( ( PN_CHARS | DOT )* PN_CHARS )?
			int alt6=2;
			try { DebugEnterSubRule(6);
			try { DebugEnterDecision(6, false);
			int LA6_1 = input.LA(1);

			if (((LA6_1>='-' && LA6_1<='.')||(LA6_1>='0' && LA6_1<='9')||(LA6_1>='A' && LA6_1<='Z')||LA6_1=='_'||(LA6_1>='a' && LA6_1<='z')||LA6_1=='\u00B7'||(LA6_1>='\u00C0' && LA6_1<='\u00D6')||(LA6_1>='\u00D8' && LA6_1<='\u00F6')||(LA6_1>='\u00F8' && LA6_1<='\u037D')||(LA6_1>='\u037F' && LA6_1<='\u1FFF')||(LA6_1>='\u200C' && LA6_1<='\u200D')||(LA6_1>='\u203F' && LA6_1<='\u2040')||(LA6_1>='\u2070' && LA6_1<='\u218F')||(LA6_1>='\u2C00' && LA6_1<='\u2FEF')||(LA6_1>='\u3001' && LA6_1<='\uD7FF')||(LA6_1>='\uF900' && LA6_1<='\uFDCF')||(LA6_1>='\uFDF0' && LA6_1<='\uFFFD')))
			{
				alt6 = 1;
			}
			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// ../Grammars/OslcOrderBy.g:108:31: ( PN_CHARS | DOT )* PN_CHARS
				{
				DebugLocation(108, 31);
				// ../Grammars/OslcOrderBy.g:108:31: ( PN_CHARS | DOT )*
				try { DebugEnterSubRule(5);
				while (true)
				{
					int alt5=2;
					try { DebugEnterDecision(5, false);
					int LA5_1 = input.LA(1);

					if ((LA5_1=='-'||(LA5_1>='0' && LA5_1<='9')||(LA5_1>='A' && LA5_1<='Z')||LA5_1=='_'||(LA5_1>='a' && LA5_1<='z')||LA5_1=='\u00B7'||(LA5_1>='\u00C0' && LA5_1<='\u00D6')||(LA5_1>='\u00D8' && LA5_1<='\u00F6')||(LA5_1>='\u00F8' && LA5_1<='\u037D')||(LA5_1>='\u037F' && LA5_1<='\u1FFF')||(LA5_1>='\u200C' && LA5_1<='\u200D')||(LA5_1>='\u203F' && LA5_1<='\u2040')||(LA5_1>='\u2070' && LA5_1<='\u218F')||(LA5_1>='\u2C00' && LA5_1<='\u2FEF')||(LA5_1>='\u3001' && LA5_1<='\uD7FF')||(LA5_1>='\uF900' && LA5_1<='\uFDCF')||(LA5_1>='\uFDF0' && LA5_1<='\uFFFD')))
					{
						int LA5_2 = input.LA(2);

						if (((LA5_2>='-' && LA5_2<='.')||(LA5_2>='0' && LA5_2<='9')||(LA5_2>='A' && LA5_2<='Z')||LA5_2=='_'||(LA5_2>='a' && LA5_2<='z')||LA5_2=='\u00B7'||(LA5_2>='\u00C0' && LA5_2<='\u00D6')||(LA5_2>='\u00D8' && LA5_2<='\u00F6')||(LA5_2>='\u00F8' && LA5_2<='\u037D')||(LA5_2>='\u037F' && LA5_2<='\u1FFF')||(LA5_2>='\u200C' && LA5_2<='\u200D')||(LA5_2>='\u203F' && LA5_2<='\u2040')||(LA5_2>='\u2070' && LA5_2<='\u218F')||(LA5_2>='\u2C00' && LA5_2<='\u2FEF')||(LA5_2>='\u3001' && LA5_2<='\uD7FF')||(LA5_2>='\uF900' && LA5_2<='\uFDCF')||(LA5_2>='\uFDF0' && LA5_2<='\uFFFD')))
						{
							alt5 = 1;
						}


					}
					else if ((LA5_1=='.'))
					{
						alt5 = 1;
					}


					} finally { DebugExitDecision(5); }
					switch ( alt5 )
					{
					case 1:
						DebugEnterAlt(1);
						// ../Grammars/OslcOrderBy.g:
						{
						DebugLocation(108, 31);
						input.Consume();


						}
						break;

					default:
						goto loop5;
					}
				}

				loop5:
					;

				} finally { DebugExitSubRule(5); }

				DebugLocation(108, 47);
				mPN_CHARS(); 

				}
				break;

			}
			} finally { DebugExitSubRule(6); }


			}

		}
		finally
		{
			TraceOut("PN_LOCAL", 11);
			LeaveRule("PN_LOCAL", 11);
			LeaveRule_PN_LOCAL();
		}
	}
	// $ANTLR end "PN_LOCAL"

	partial void EnterRule_PN_CHARS_BASE();
	partial void LeaveRule_PN_CHARS_BASE();

	// $ANTLR start "PN_CHARS_BASE"
	[GrammarRule("PN_CHARS_BASE")]
	private void mPN_CHARS_BASE()
	{
		EnterRule_PN_CHARS_BASE();
		EnterRule("PN_CHARS_BASE", 12);
		TraceIn("PN_CHARS_BASE", 12);
		try
		{
			// ../Grammars/OslcOrderBy.g:113:5: ( 'A' .. 'Z' | 'a' .. 'z' | '\\u00C0' .. '\\u00D6' | '\\u00D8' .. '\\u00F6' | '\\u00F8' .. '\\u02FF' | '\\u0370' .. '\\u037D' | '\\u037F' .. '\\u1FFF' | '\\u200C' .. '\\u200D' | '\\u2070' .. '\\u218F' | '\\u2C00' .. '\\u2FEF' | '\\u3001' .. '\\uD7FF' | '\\uF900' .. '\\uFDCF' | '\\uFDF0' .. '\\uFFFD' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:
			{
			DebugLocation(113, 5);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z')||(input.LA(1)>='\u00C0' && input.LA(1)<='\u00D6')||(input.LA(1)>='\u00D8' && input.LA(1)<='\u00F6')||(input.LA(1)>='\u00F8' && input.LA(1)<='\u02FF')||(input.LA(1)>='\u0370' && input.LA(1)<='\u037D')||(input.LA(1)>='\u037F' && input.LA(1)<='\u1FFF')||(input.LA(1)>='\u200C' && input.LA(1)<='\u200D')||(input.LA(1)>='\u2070' && input.LA(1)<='\u218F')||(input.LA(1)>='\u2C00' && input.LA(1)<='\u2FEF')||(input.LA(1)>='\u3001' && input.LA(1)<='\uD7FF')||(input.LA(1)>='\uF900' && input.LA(1)<='\uFDCF')||(input.LA(1)>='\uFDF0' && input.LA(1)<='\uFFFD'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("PN_CHARS_BASE", 12);
			LeaveRule("PN_CHARS_BASE", 12);
			LeaveRule_PN_CHARS_BASE();
		}
	}
	// $ANTLR end "PN_CHARS_BASE"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 13);
		TraceIn("DIGIT", 13);
		try
		{
			// ../Grammars/OslcOrderBy.g:130:5: ( '0' .. '9' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:
			{
			DebugLocation(130, 5);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 13);
			LeaveRule("DIGIT", 13);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_DOT();
	partial void LeaveRule_DOT();

	// $ANTLR start "DOT"
	[GrammarRule("DOT")]
	private void mDOT()
	{
		EnterRule_DOT();
		EnterRule("DOT", 14);
		TraceIn("DOT", 14);
		try
		{
			// ../Grammars/OslcOrderBy.g:135:5: ( '.' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:135:7: '.'
			{
			DebugLocation(135, 7);
			Match('.'); 

			}

		}
		finally
		{
			TraceOut("DOT", 14);
			LeaveRule("DOT", 14);
			LeaveRule_DOT();
		}
	}
	// $ANTLR end "DOT"

	partial void EnterRule_EOL();
	partial void LeaveRule_EOL();

	// $ANTLR start "EOL"
	[GrammarRule("EOL")]
	private void mEOL()
	{
		EnterRule_EOL();
		EnterRule("EOL", 15);
		TraceIn("EOL", 15);
		try
		{
			// ../Grammars/OslcOrderBy.g:140:5: ( '\\n' | '\\r' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:
			{
			DebugLocation(140, 5);
			if (input.LA(1)=='\n'||input.LA(1)=='\r')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("EOL", 15);
			LeaveRule("EOL", 15);
			LeaveRule_EOL();
		}
	}
	// $ANTLR end "EOL"

	partial void EnterRule_OPEN_CURLY_BRACE();
	partial void LeaveRule_OPEN_CURLY_BRACE();

	// $ANTLR start "OPEN_CURLY_BRACE"
	[GrammarRule("OPEN_CURLY_BRACE")]
	private void mOPEN_CURLY_BRACE()
	{
		EnterRule_OPEN_CURLY_BRACE();
		EnterRule("OPEN_CURLY_BRACE", 16);
		TraceIn("OPEN_CURLY_BRACE", 16);
		try
		{
			int _type = OPEN_CURLY_BRACE;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:143:5: ( '{' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:143:7: '{'
			{
			DebugLocation(143, 7);
			Match('{'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OPEN_CURLY_BRACE", 16);
			LeaveRule("OPEN_CURLY_BRACE", 16);
			LeaveRule_OPEN_CURLY_BRACE();
		}
	}
	// $ANTLR end "OPEN_CURLY_BRACE"

	partial void EnterRule_CLOSE_CURLY_BRACE();
	partial void LeaveRule_CLOSE_CURLY_BRACE();

	// $ANTLR start "CLOSE_CURLY_BRACE"
	[GrammarRule("CLOSE_CURLY_BRACE")]
	private void mCLOSE_CURLY_BRACE()
	{
		EnterRule_CLOSE_CURLY_BRACE();
		EnterRule("CLOSE_CURLY_BRACE", 17);
		TraceIn("CLOSE_CURLY_BRACE", 17);
		try
		{
			int _type = CLOSE_CURLY_BRACE;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:147:5: ( '}' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:147:7: '}'
			{
			DebugLocation(147, 7);
			Match('}'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CLOSE_CURLY_BRACE", 17);
			LeaveRule("CLOSE_CURLY_BRACE", 17);
			LeaveRule_CLOSE_CURLY_BRACE();
		}
	}
	// $ANTLR end "CLOSE_CURLY_BRACE"

	partial void EnterRule_PLUS();
	partial void LeaveRule_PLUS();

	// $ANTLR start "PLUS"
	[GrammarRule("PLUS")]
	private void mPLUS()
	{
		EnterRule_PLUS();
		EnterRule("PLUS", 18);
		TraceIn("PLUS", 18);
		try
		{
			// ../Grammars/OslcOrderBy.g:153:5: ( '+' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:153:7: '+'
			{
			DebugLocation(153, 7);
			Match('+'); 

			}

		}
		finally
		{
			TraceOut("PLUS", 18);
			LeaveRule("PLUS", 18);
			LeaveRule_PLUS();
		}
	}
	// $ANTLR end "PLUS"

	partial void EnterRule_MINUS();
	partial void LeaveRule_MINUS();

	// $ANTLR start "MINUS"
	[GrammarRule("MINUS")]
	private void mMINUS()
	{
		EnterRule_MINUS();
		EnterRule("MINUS", 19);
		TraceIn("MINUS", 19);
		try
		{
			// ../Grammars/OslcOrderBy.g:158:5: ( '-' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:158:7: '-'
			{
			DebugLocation(158, 7);
			Match('-'); 

			}

		}
		finally
		{
			TraceOut("MINUS", 19);
			LeaveRule("MINUS", 19);
			LeaveRule_MINUS();
		}
	}
	// $ANTLR end "MINUS"

	partial void EnterRule_ASTERISK();
	partial void LeaveRule_ASTERISK();

	// $ANTLR start "ASTERISK"
	[GrammarRule("ASTERISK")]
	private void mASTERISK()
	{
		EnterRule_ASTERISK();
		EnterRule("ASTERISK", 20);
		TraceIn("ASTERISK", 20);
		try
		{
			int _type = ASTERISK;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:161:5: ( '*' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:161:7: '*'
			{
			DebugLocation(161, 7);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASTERISK", 20);
			LeaveRule("ASTERISK", 20);
			LeaveRule_ASTERISK();
		}
	}
	// $ANTLR end "ASTERISK"

	partial void EnterRule_COMMA();
	partial void LeaveRule_COMMA();

	// $ANTLR start "COMMA"
	[GrammarRule("COMMA")]
	private void mCOMMA()
	{
		EnterRule_COMMA();
		EnterRule("COMMA", 21);
		TraceIn("COMMA", 21);
		try
		{
			int _type = COMMA;
			int _channel = DefaultTokenChannel;
			// ../Grammars/OslcOrderBy.g:165:5: ( ',' )
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:165:7: ','
			{
			DebugLocation(165, 7);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMA", 21);
			LeaveRule("COMMA", 21);
			LeaveRule_COMMA();
		}
	}
	// $ANTLR end "COMMA"

	public override void mTokens()
	{
		// ../Grammars/OslcOrderBy.g:1:8: ( SCOPED_TERM | SIMPLE_TERM | TERMS | WS | PNAME_NS | PNAME_LN | DIRECTION | OPEN_CURLY_BRACE | CLOSE_CURLY_BRACE | ASTERISK | COMMA )
		int alt7=11;
		try { DebugEnterDecision(7, false);
		try
		{
			alt7 = dfa7.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(7); }
		switch (alt7)
		{
		case 1:
			DebugEnterAlt(1);
			// ../Grammars/OslcOrderBy.g:1:10: SCOPED_TERM
			{
			DebugLocation(1, 10);
			mSCOPED_TERM(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// ../Grammars/OslcOrderBy.g:1:22: SIMPLE_TERM
			{
			DebugLocation(1, 22);
			mSIMPLE_TERM(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// ../Grammars/OslcOrderBy.g:1:34: TERMS
			{
			DebugLocation(1, 34);
			mTERMS(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// ../Grammars/OslcOrderBy.g:1:40: WS
			{
			DebugLocation(1, 40);
			mWS(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// ../Grammars/OslcOrderBy.g:1:43: PNAME_NS
			{
			DebugLocation(1, 43);
			mPNAME_NS(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// ../Grammars/OslcOrderBy.g:1:52: PNAME_LN
			{
			DebugLocation(1, 52);
			mPNAME_LN(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// ../Grammars/OslcOrderBy.g:1:61: DIRECTION
			{
			DebugLocation(1, 61);
			mDIRECTION(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// ../Grammars/OslcOrderBy.g:1:71: OPEN_CURLY_BRACE
			{
			DebugLocation(1, 71);
			mOPEN_CURLY_BRACE(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// ../Grammars/OslcOrderBy.g:1:88: CLOSE_CURLY_BRACE
			{
			DebugLocation(1, 88);
			mCLOSE_CURLY_BRACE(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// ../Grammars/OslcOrderBy.g:1:106: ASTERISK
			{
			DebugLocation(1, 106);
			mASTERISK(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// ../Grammars/OslcOrderBy.g:1:115: COMMA
			{
			DebugLocation(1, 115);
			mCOMMA(); 

			}
			break;

		}

	}


	#region DFA
	DFA7 dfa7;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa7 = new DFA7(this);
	}

	private class DFA7 : DFA
	{
		private const string DFA7_eotS =
			"\x5\xFFFF\x1\x10\x14\xFFFF\x1\x1D\xB\xFFFF\x1\x28\x1\x29\x2\xFFFF";
		private const string DFA7_eofS =
			"\x2A\xFFFF";
		private const string DFA7_minS =
			"\x1\x9\x2\x2D\x1\xFFFF\x1\x2D\x1\x30\x5\xFFFF\x5\x2D\x2\xFFFF\xB\x2D"+
			"\x1\xFFFF\xA\x2D\x2\xFFFF";
		private const string DFA7_maxS =
			"\x3\xFFFD\x1\xFFFF\x2\xFFFD\x5\xFFFF\x5\xFFFD\x2\xFFFF\xB\xFFFD\x1\xFFFF"+
			"\xA\xFFFD\x2\xFFFF";
		private const string DFA7_acceptS =
			"\x3\xFFFF\x1\x4\x2\xFFFF\x1\x7\x1\x8\x1\x9\x1\xA\x1\xB\x5\xFFFF\x1\x5"+
			"\x1\x6\xB\xFFFF\x1\x3\xA\xFFFF\x1\x1\x1\x2";
		private const string DFA7_specialS =
			"\x2A\xFFFF}>";
		private static readonly string[] DFA7_transitionS =
			{
				"\x2\x3\x2\xFFFF\x1\x3\x12\xFFFF\x1\x3\x9\xFFFF\x1\x9\x1\x6\x1\xA\x1"+
				"\x6\xC\xFFFF\x1\x5\x6\xFFFF\x1A\x4\x6\xFFFF\x12\x4\x1\x1\x1\x2\x6\x4"+
				"\x1\x7\x1\xFFFF\x1\x8\x42\xFFFF\x17\x4\x1\xFFFF\x1F\x4\x1\xFFFF\x208"+
				"\x4\x70\xFFFF\xE\x4\x1\xFFFF\x1C81\x4\xC\xFFFF\x2\x4\x62\xFFFF\x120"+
				"\x4\xA70\xFFFF\x3F0\x4\x11\xFFFF\xA7FF\x4\x2100\xFFFF\x4D0\x4\x20\xFFFF"+
				"\x20E\x4",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x2\xD\x1\xB\x5\xD\x1\xC\x11\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD"+
				"\x1\xFFFF\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31"+
				"\xFFFF\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD"+
				"\x2100\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x4\xD\x1\xF\x15\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF"+
				"\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF"+
				"\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20"+
				"\xFFFF\x20E\xD",
				"\xA\x11\x7\xFFFF\x1A\x11\x4\xFFFF\x1\x11\x1\xFFFF\x1A\x11\x45\xFFFF"+
				"\x17\x11\x1\xFFFF\x1F\x11\x1\xFFFF\x208\x11\x70\xFFFF\xE\x11\x1\xFFFF"+
				"\x1C81\x11\xC\xFFFF\x2\x11\x62\xFFFF\x120\x11\xA70\xFFFF\x3F0\x11\x11"+
				"\xFFFF\xA7FF\x11\x2100\xFFFF\x4D0\x11\x20\xFFFF\x20E\x11",
				"",
				"",
				"",
				"",
				"",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xE\xD\x1\x12\xB\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xC\xD\x1\x13\xD\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF"+
				"\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF"+
				"\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20"+
				"\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x7\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1\xFFFF"+
				"\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF\x286"+
				"\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF\x120"+
				"\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20\xFFFF"+
				"\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x11\xD\x1\x14\x8\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"",
				"",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xF\xD\x1\x15\xA\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xF\xD\x1\x16\xA\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xC\xD\x1\x17\xD\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x4\xD\x1\x18\x15\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xB\xD\x1\x19\xE\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x12\xD\x1\x1A\x7\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x3\xD\x1\x1B\x16\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x4\xD\x1\x1C\x15\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF"+
				"\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF"+
				"\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20"+
				"\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\x1E\x1"+
				"\xFFFF\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF"+
				"\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF"+
				"\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20"+
				"\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\x1F\x1"+
				"\xFFFF\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF"+
				"\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF"+
				"\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20"+
				"\xFFFF\x20E\xD",
				"",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x13\xD\x1\x20\x6\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x13\xD\x1\x21\x6\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x4\xD\x1\x22\x15\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x4\xD\x1\x23\x15\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x11\xD\x1\x24\x8\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x11\xD\x1\x25\x8\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF"+
				"\x1F\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF"+
				"\x2\xD\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100"+
				"\xFFFF\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xC\xD\x1\x26\xD\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\xC\xD\x1\x27\xD\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F"+
				"\xD\x1\xFFFF\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD"+
				"\x2F\xFFFF\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF"+
				"\x4D0\xD\x20\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF"+
				"\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF"+
				"\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20"+
				"\xFFFF\x20E\xD",
				"\x1\xD\x1\xE\x1\xFFFF\xA\xD\x1\x5\x6\xFFFF\x1A\xD\x4\xFFFF\x1\xD\x1"+
				"\xFFFF\x1A\xD\x3C\xFFFF\x1\xD\x8\xFFFF\x17\xD\x1\xFFFF\x1F\xD\x1\xFFFF"+
				"\x286\xD\x1\xFFFF\x1C81\xD\xC\xFFFF\x2\xD\x31\xFFFF\x2\xD\x2F\xFFFF"+
				"\x120\xD\xA70\xFFFF\x3F0\xD\x11\xFFFF\xA7FF\xD\x2100\xFFFF\x4D0\xD\x20"+
				"\xFFFF\x20E\xD",
				"",
				""
			};

		private static readonly short[] DFA7_eot = DFA.UnpackEncodedString(DFA7_eotS);
		private static readonly short[] DFA7_eof = DFA.UnpackEncodedString(DFA7_eofS);
		private static readonly char[] DFA7_min = DFA.UnpackEncodedStringToUnsignedChars(DFA7_minS);
		private static readonly char[] DFA7_max = DFA.UnpackEncodedStringToUnsignedChars(DFA7_maxS);
		private static readonly short[] DFA7_accept = DFA.UnpackEncodedString(DFA7_acceptS);
		private static readonly short[] DFA7_special = DFA.UnpackEncodedString(DFA7_specialS);
		private static readonly short[][] DFA7_transition;

		static DFA7()
		{
			int numStates = DFA7_transitionS.Length;
			DFA7_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA7_transition[i] = DFA.UnpackEncodedString(DFA7_transitionS[i]);
			}
		}

		public DFA7( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 7;
			this.eot = DFA7_eot;
			this.eof = DFA7_eof;
			this.min = DFA7_min;
			this.max = DFA7_max;
			this.accept = DFA7_accept;
			this.special = DFA7_special;
			this.transition = DFA7_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( SCOPED_TERM | SIMPLE_TERM | TERMS | WS | PNAME_NS | PNAME_LN | DIRECTION | OPEN_CURLY_BRACE | CLOSE_CURLY_BRACE | ASTERISK | COMMA );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}
