//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSLC4Net.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSLC4Net.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   OSLC001: Error unregistering Service Provider URI {0}. Returned error code is: {1}; error message is: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeregistrationException {
            get {
                return ResourceManager.GetString("DeregistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC002: Duplicate property definition annotation {1} for class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DuplicatePropertyDefinitionException {
            get {
                return ResourceManager.GetString("DuplicatePropertyDefinitionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid occurs annotation {2} for method {1} of class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOccursException {
            get {
                return ResourceManager.GetString("InvalidOccursException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC004: Invalid property definition annotation {2} for method {1} of class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidPropertyDefinitionException {
            get {
                return ResourceManager.GetString("InvalidPropertyDefinitionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC005: Invalid property type {2} returned by method {1} of class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidPropertyTypeException {
            get {
                return ResourceManager.GetString("InvalidPropertyTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC006: Invalid representation {2} defined for method {1} of class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRepresentationException {
            get {
                return ResourceManager.GetString("InvalidRepresentationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC007: Invalid value type {2} defined for method {1} of class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidValueTypeException {
            get {
                return ResourceManager.GetString("InvalidValueTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC008: Missing mandatory OSLC annotation {1} for class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MissingAnnotationException {
            get {
                return ResourceManager.GetString("MissingAnnotationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC009: Namespace declaration not defined for namespace {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MissingNamespaceDeclarationException {
            get {
                return ResourceManager.GetString("MissingNamespaceDeclarationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC010: Namespace declaration not defined for prefix {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MissingNamespacePrefixException {
            get {
                return ResourceManager.GetString("MissingNamespacePrefixException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC011: Missing corresponding set method for method {1} of class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MissingSetMethodException {
            get {
                return ResourceManager.GetString("MissingSetMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC012: Multiple values for method {1} of class {0} that supports at most one value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MisusedOccursException {
            get {
                return ResourceManager.GetString("MisusedOccursException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC013: Error registering Service Provider {0}. Returned error code is: {1}; error message is: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistrationException {
            get {
                return ResourceManager.GetString("RegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSLC014: Relative URI value {2} for method {1} of class {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelativeURIException {
            get {
                return ResourceManager.GetString("RelativeURIException", resourceCulture);
            }
        }
    }
}
