# This is a basic workflow to help you get started with Actions
name: 'CI (.NET Framework)'

on:
  push:
    branches: [ 'main', 'master' ]
  pull_request:
    branches: [ 'main', 'master' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3.2
      # with:
      #   vs-version: '[17.5.3,18.0.0)'
      #   msbuild-architecture: x64

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - uses: actions/cache@v4
      with:
        path: |
            ${{ github.workspace }}/.nuget/packages
        # OSLC4Net_NETFramework/packages/
        # OSLC4Net_NETFramework/**/*.nuget.g.props
        # OSLC4Net_NETFramework/**/*.nuget.g.targets
        # OSLC4Net_NETFramework/**/project.assets.json
        # OSLC4Net_NETFramework/**/bin/
        # OSLC4Net_NETFramework/**/obj/
        key: ${{ runner.os }}-nuget-${{ hashFiles('.github/workflows/main.yml', '.github/workflows/netframework.yml',  '**/packages.config', '**/packages.lock.json', '**/*.sln', '**/*.csproj') }}
        # restore-keys: |
    #       ${{ runner.os }}-nuget-

    - name: Restore NuGet Packages
      run: nuget restore OSLC4Net_NETFramework/OSLC4Net_NETFramework.sln

    - name: Build OSLC4Net
      # /p:Configuration=Release is about 3x faster in Actions,
      # not sure of the implications for VStest
      run: msbuild OSLC4Net_NETFramework/OSLC4Net_NETFramework.sln /p:Configuration=Release
      #run: msbuild OSLC4Net_NETFramework/OSLC4Net_NETFramework.sln

    - name: Run VStest
      uses: microsoft/vstest-action@v1.0.0
      with:
        # see https://github.com/OSLC/oslc4net/issues/57
        testAssembly: |
            **\\bin\\*\\*Test*.dll
            !**\\OSLC4Net.ChangeManagementTest\\**\*
        # OBS! searchFolder must be terminated
        searchFolder: '.\OSLC4Net_NETFramework\'
        runInParallel: true
