name: Rebase
on:
  # schedule:
  #   - cron:  '40 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rebase:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: peter-evans/rebase@e4945786f7ca41fe6e101cead4395f5489593943 # v4.0.0
        with:
          token: ${{ secrets.GH_PAT }}
          exclude-labels: |
            no-rebase
            dependencies
          # exclude-drafts: true
